### ISSUE TITLE
Calibrating a trained model

### ISSUE THREAD

**Issue by vinith-reddy25** [stanford-oval/decaNLP#247]
When I ran 

$genienlp calibrate --confidence_path <confidence_feature_file> --save <calibrator_directory> --name_prefix <calibrator_name>

then I'm getting this error:

in "genienlp/calibrator.py",  line 74, in <lambda>

return lambda x: torch.var(x[i].drop_logits, dim=0).view(-1)

TypeError: var() received an invalid combination of arguments - got (NoneType, dim=int), but expected one of:
 * (Tensor input, tuple of names dim, bool unbiased, bool keepdim, *, Tensor out)
 * (Tensor input, tuple of ints dim, bool unbiased, bool keepdim, *, Tensor out)
 * (Tensor input, bool unbiased)
      didn't match because some of the keywords were incorrect: dim

**Comment by s-jse** [comment]
Hi! And thanks for opening this issue.

Please note that calibrating trained models is completely optional. Calibration is used for obtaining a better estimate of a neural networks confidence in its predictions, and in fact, most applications do not need calibration at all.

1. What neural model are you using? It would be really helpful if you could let us know the arguments you are using in your `genienlp train` command.
2. As our documentation suggests, there are three steps necessary to do calibration: https://github.com/stanford-oval/genienlp#calibrating-a-trained-model.
Can you please let us know the exact command you are running for each one of these steps, and whether they produce the expected outputs? If not, what error message do they print?

**Comment by Shisir99** [comment]
we generated pickle fie using the following command:genienlp predict --tasks almond --data /home/venkata_vamsi/Desktop/demo/order.tea/workdir --path models/seqnewmodel --evaluate valid --eval_dir workdir/almond/ --save_confidence_features --confidence_feature_path models/seqnewmodel/calibrator.pickle so after generating pickle file, we ran the second command : (genienlp server --path /home/venkata_vamsi/Desktop/demo/order.tea/models/seqnewmodel --calibrator_paths /home/venkata_vamsi/Desktop/demo/order.tea/models/seqnewmodel/calibrator.pickle --stdin )but we are getting the below error: Traceback (most recent call last):

  File "/home/venkata_vamsi/.local/bin/genienlp", line 8, in <module>

    sys.exit(main())

  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/genienlp/__main__.py", line 97, in main

    subcommands[argv.subcommand][2](argv)

  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/genienlp/server.py", line 319, in main

    model, device, confidence_estimators, estimator_filenames, bootleg_annotator = init(args)

  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/genienlp/server.py", line 310, in init

    estimator = ConfidenceEstimator.load(path)

  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/genienlp/calibrate.py", line 378, in load

    obj = dill.load(f)

  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/dill/_dill.py", line 313, in load

    return Unpickler(file, ignore=ignore, **kwds).load()

  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/dill/_dill.py", line 525, in load

    obj = StockUnpickler.load(self)

_pickle.UnpicklingError: A load persistent id instruction was encountered,

but no persistent_load function was specified. so we didn't went for running the next command

**Comment by s-jse** [comment]
OK, to clarify, the three steps (from here https://github.com/stanford-oval/genienlp#calibrating-a-trained-model) are as follows.
You are running step 1, then step 3. You need to run step 2 before step 3.

Step 1:
Run `genienlp predict --tasks almond --data /home/venkata_vamsi/Desktop/demo/order.tea/workdir --path models/seqnewmodel --evaluate valid --eval_dir workdir/almond/ --save_confidence_features --confidence_feature_path models/seqnewmodel/confidences.pkl`
Now you have a file called `confidences.pkl`. Note that this is NOT the calibrator itself. This is simply a numpy array of extracted confidence features, hence the argument is called `--save_confidence_features `.

Step 2:
Run `genienlp calibrate --confidence_path <confidence_feature_file> --save <calibrator_directory> --name_prefix <calibrator_name>` for example `genienlp calibrate --confidence_path models/seqnewmodel/confidences.pkl --save models/seqnewmodel/ --name_prefix calibrator`

You should get the file `models/seqnewmodel/calibrator.calib`. This file contains the weights of a trained boosted tree.

Step 3:
Run `genienlp server --path /home/venkata_vamsi/Desktop/demo/order.tea/models/seqnewmodel --calibrator_paths models/seqnewmodel/calibrator.calib --stdin`

Let me know if this works.

**Comment by venkatvamsi1** [comment]
![Screenshot from 2022-02-10 13-45-55](https://user-images.githubusercontent.com/99391053/153365616-ff2c67fe-6c68-4008-ba1b-6bd14e904ce1.png)
![Screenshot from 2022-02-10 13-46-06](https://user-images.githubusercontent.com/99391053/153365642-17b61660-3f2d-48f3-bbb0-6e699f316809.png)

followed the above steps mentioned. but for step two getting this way. please find the attached screenshots

**Comment by vinith-reddy25** [comment]
@s-jse waiting for your response.

**Comment by s-jse** [comment]
I'm still trying to reproduce this error. My guess is that there is something irregular with your dataset because you are getting score=1 with `raw_seq_prob`. This usually happens when the accuracy on the dataset is either 100% or 0% (i.e. one of the classes of correct or incorrect answers is empty).

- You can comment out the tuple that causes this error (and any subsequent error) from the [feature sets](https://github.com/stanford-oval/genienlp/blob/master/genienlp/calibrate.py#L598) to make the code get through the calibration. But the resulting calibrator is essentially useless, given the above issue.

- The more information about the dataset you provide, the easier it becomes for me to reproduce this error.

- Also, please let me know which model you are using. Is it `TransformerSeq2Seq` or `TransformerLSTM`?

**Comment by venkatvamsi1** [comment]
we are using TransformerSeq2Seq

At starting we tried to generate the dataset from first five steps of this link : https://github.com/stanford-oval/genie-toolkit/blob/master/doc/tutorial-basic.md
 
but later I created a own train.tsv with 26 rows.

Our usecase is ordering pizza / coffee. Can you help us in creating a dataset? Please accept linkedin request @s-jse

**Comment by vinith-reddy25** [comment]
@s-jse We downloaded baseline model(wget https://almond-static.stanford.edu/research/tutorials/baseline.tar.xz) which is of com.yelp skill. For running step 1, I need train.tsv, or eval.tsv. Can @s-jse provide this files??

or

Can we get any model along with their train.tsv, eval.tsv

**Comment by s-jse** [comment]
Just to clarify, I don't think this issue has to do with the calibration code, but the model you are using.
I'm going to package and upload a model we have trained and its dataset, after the weekend.
Please let us know if the issue remains after you try calibration on that model.

**Comment by vinith-reddy25** [comment]
Gentle Reminder.

**Comment by s-jse** [comment]
I've uploaded a BART model trained on the [Schema2QA](https://github.com/stanford-oval/schema2qa) dataset in the restaurant domain. You can read more about this dataset in its repository.

- Model: [restaurant_model.tar.xz](https://almond-static.stanford.edu/research/schema2qa2.0/restaurant_model.tar.xz)

- Data: the data is available through the Schema2QA repository. Specifically, you can access the training data [here](https://almond-static.stanford.edu/research/schema2qa2.0/schema2qa.tar.xz), (the file named `restaurant.tsv`), and the validation set [here](https://raw.githubusercontent.com/stanford-oval/schema2qa/main/restaurants/eval/annotated.tsv). Copy these two files and rename them so that your data directory looks like the usual genienlp format, i.e. `datadir/almond/train.tsv` and `datadir/almond/eval.tsv`.

The accuracy of this model on this validation set is 76.52%.
You can then use `eval.tsv` to calibrate the model.

**Comment by venkatvamsi192324** [comment]
Hi @s-jse , we used the same model you sent us. we ran the first command :

( $ **genienlp predict --tasks almond --data /home/venkata_vamsi/Desktop/demo/order.tea/workdir --path models/seqnewmodel --evaluate valid --eval_dir workdir/almond/ --save_confidence_features --confidence_feature_path models/seqnewmodel/confidences.pkl** )

for generating pickle file and next when we are running the second command:

i.e, $ **genienlp calibrate --confidence_path <confidence_feature_file> --save <calibrator_directory> --name_prefix <calibrator_name> for example genienlp calibrate --confidence_path models/seqnewmodel/confidences.pkl --save models/seqnewmodel/ --name_prefix calibrator**

we are getting the below error :Traceback (most recent call last):

  File "/home/venkata_vamsi/.local/bin/genienlp", line 8, in <module>
    sys.exit(main())
  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/genienlp/__main__.py", line 97, in main
    subcommands[argv.subcommand][2](argv)
  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/genienlp/calibrate.py", line 745, in main
    train_features, train_labels = estimator.convert_to_dataset(train_confidences, train=True)
  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/genienlp/calibrate.py", line 352, in convert_to_dataset
    features = self.convert_to_features(confidences, train)
  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/genienlp/calibrate.py", line 513, in convert_to_features
    feature = [featurizer(c) for c in confidences]  # list of np.arrays
  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/genienlp/calibrate.py", line 513, in <listcomp>
    feature = [featurizer(c) for c in confidences]  # list of np.arrays
  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/genienlp/calibrate.py", line 53, in <lambda>
    return lambda x: f(x).max().view(-1)
  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/genienlp/calibrate.py", line 70, in f
    a = torch.sqrt(var_drop_logit(i)(x)) / mean_drop_logit(i)(x)
  File "/home/venkata_vamsi/.local/lib/python3.8/site-packages/genienlp/calibrate.py", line 79, in <lambda>
    return lambda x: torch.var(x[i].drop_logits, dim=0).view(-1)
TypeError: var() received an invalid combination of arguments - got (NoneType, dim=int), but expected one of:
 * (Tensor input, tuple of names dim, bool unbiased, bool keepdim, *, Tensor out)
 * (Tensor input, tuple of ints dim, bool unbiased, bool keepdim, *, Tensor out)
 * (Tensor input, bool unbiased)
      didn't match because some of the keywords were incorrect: dim

.
.
.




And we printed the x using logs and we get this:
[<Confidence: drop_logits=None, drop_probs=None, first_mistake=7, nodrop_logits=tensor([22.8892, 42.4272, 48.7284, 44.4690, 42.6317, 44.7761, 51.2762, 27.1848,
        38.9938, 33.9231, 37.8598, 44.1898, 46.1895, 45.4581, 49.8617, 40.9607,
        44.1213, 45.4373, 38.8678, 47.1695, 50.0211, 42.4427, 47.6551, 30.8959,
        35.4173]), nodrop_probs=tensor([0.9898, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9876, 1.0000,
        1.0000, 0.9898, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9009, 1.0000]), nodrop_entropies=tensor([6.6991e-02, 1.1114e-08, 6.1361e-10, 7.4472e-09, 1.8433e-07, 5.9787e-09,
        1.5641e-11, 6.6743e-02, 4.3072e-07, 5.5963e-05, 5.6796e-02, 4.1397e-05,
        5.6647e-09, 3.0519e-07, 3.5573e-08, 1.0432e-05, 5.2419e-07, 1.0945e-08,
        5.5329e-07, 7.8097e-09, 9.0124e-08, 6.6547e-09, 2.3969e-07, 3.2310e-01,
        1.3834e-07]), context=tensor([    0, 13724,    62,  4329,    11,  5573,  5030, 16306,     2]), label=False>]


![Screenshot from 2022-02-22 11-52-04](https://user-images.githubusercontent.com/51965659/155074677-b2a68134-2709-40e7-b1ec-f7a023719d5e.png)

Please find the screenshot for your [reference.]

**Comment by vinith-reddy25** [comment]
Can someone share other methods to get score, otherthan "Calibrating a trained model" method? @s-jse can you try to generate ".calib" file. If you didn't getting drop_logits= None, and able to get scores then let us know.

**Comment by s-jse** [comment]
In the first command, you need to also use `--mc_dropout_num 1`. Otherwise, the features related to Monte Carlo dropout (stored in drop_logits) are not generated. `--mc_dropout_num 5` runs slower, and is only useful for applications that really need the increased calibration accuracy.

**Comment by vinith-reddy25** [comment]
It is coming.

**Comment by venkatvamsi192324** [comment]
Hi, we are getting the score using above info. Can I know what is 1 or 5 means in **--mc_dropout_num 1 or 5**  or any possible reference can also helpful. 

We are getting proper score for the input which we trained (i.e., around 0.6-0.98). Also we are getting high score for some random inputs(example: "how are you" i.e., above 0.95) which aren't trained. This is for a model we developed which has only one skill i.e., order coffee. Is this high score issue for random input is because of only one skill we are using?

Is there any other ways to get score other-than "Calibrating a trained model" method?

**Comment by s-jse** [comment]
**Q: What is `--mc_dropout_num`?
A: `--mc_dropout_num` determines the number of times we ensemble the model with itself.**
For example, `mc_dropout_num 5` means we run the model 5 times (so running the commands becomes 5 times slower) and aggregate the outputs to get a better estimation compared to just running it once. The improvement, however, is rather small in practice.
This method is called Monte Carlo dropout. We don't have a good reference on it but
 [this rather long blog post](https://towardsdatascience.com/monte-carlo-dropout-7fd52f8b6571) explains how it is used for uncertainty estimation.

**Q: Is there a better way of extracting scores from trained models than using GenieNLP's calibration?
A: Not really.**

In our terminology, the score you are looking for is called confidence score, and the task of finding that score is called confidence estimation or calibration. When you calibrate a trained model in GenieNLP, it runs multiple methods for confidence estimation, and chooses the best one, i.e. the one that gives the largest area under the precision-recall curve (AUCPR). This means we look for a method that gives high scores to "desirable" outputs and low scores to "undesirable" ones.
You can see a sample precision-recall curve for one of our models below. Each line is one of the methods GenieNLP tries, and the method with the largest area under this curve is selected by default. You can get a plot similar to this one by adding `--plot` to your `genienlp calibrate ...` command.

![is_correct_precision-recall](https://user-images.githubusercontent.com/60150701/155412398-56d7dd20-78c0-4792-9f8d-bd0c86f1adda.svg)

It is worth noting that other implementations usually only go with the method we call `raw_seq_prob` in this plot, which is usually worse (how much worse depends on the specific dataset and model).
Obtaining better scores is an active area of research, and most of the publications are on image datasets, with marginal improvements over `raw_seq_prob`.

**Q: Why is calibration in GenieNLP not doing what I want?
A: Because you are asking it to do something else entirely.**
The scores that the calibrator outputs try to match what **you** deem "desirable" and "undesirable" outputs, i.e. it learns from your data. In our use cases, we typically use `eval.tsv` for calibration. This mean "desirable" outputs are the ones that the model is predicting correctly and "undesirable" outputs are the ones that the model is predicting incorrectly. Note that all of the inputs here are in-domain, i.e. they are still sentences about your coffee skill. With this, the calibrator becomes an "in-domain error detection" model. In other words, using `eval.tsv` to calibrate will give you high scores on the outputs that the model thinks it is predicting correctly, and low scores on the output that the model thinks it is predicting incorrectly, **given that the input is sufficiently similar to the examples in `eval.tsv`** (i.e. about ordering coffee).
What you are using this calibrator for, is the different task of out-of-domain detection.
Out-of-domain detection without having any out-of-domain data during training or calibration is extremely difficult, and are rarely used in practice outside research papers. 

**Q: How do I get calibration to do this so-called out-of-domain detection?
A: You need to add many out-of-domain examples to your `eval.tsv`**
The label for them (i.e. the third column in `eval.tsv`) should be something like `$ood `. Then add `--override_confidence_labels $ood` to your first `genienlp predict ...` command when calibrating.

**Q: Will this give me a decent out-of-domain detection model?
A: Maybe, or maybe not. This approach has not been tested externally, and is not an intended use case of GenieNLP.**
In practice, most people collect large datasets for their out-of-domain detection task and then use a completely separate classification model to classify what is or is not out-of-domain.

**Q: Are there any other practical issues I may encounter?
A: Yes, if the neural model you are using is not properly trained, nothing can get you the scores you want.**
This means you need to have a large enough training and validation sets. Ideally, thousands of training examples and hundreds of validation examples.
Also, no method is perfect. As you can see, for example AUCPR in the above plot is not 100. This means you should not rely on eyeballing a handful of examples to see if the scores you are getting are meaningful or not. You should use a large enough eval.tsv file (with out-of-domains if you are using this for out-of-domain detection) and then look at the precision-recall curve that `genienlp calibrate ... --plot` gives you. Anything above a straight line means the calibrator is doing something non-trivial and potentially useful.

**Comment by s-jse** [comment]
I added `--mc_dropout_num` to the calibration section of our documentation. Feel free to reopen this issue if you encounter any bugs.
