### ISSUE TITLE
Transfer learning

### ISSUE THREAD

**Issue by Shisir99** [stanford-oval/decaNLP#254]
Hello, can we use transfer learning while adding a new skill and use the pretrained model for the other skills to train this model for the new skill?

**Comment by s-jse** [comment]
In general, yes you can.
Once you have a trained model, you can use it to initialize the model in your second training. Simply add  `--load best.pth` to your second `genienlp train` command. This will load the model from the best checkpoint from the directory you specify in `--save` and will continue training the model on the dataset at `--data`. Something like this would work:

1. `genienlp train --dataset <first_dataset_directory> --save <model_directory> ...`
2. `genienlp train --dataset <second_dataset_directory> --save <model_directory> --load best.pth ...`

**Comment by Shisir99** [comment]
okay, thanks

**Comment by Shisir99** [comment]
hello, i have the model stored in the directory /home/ubuntu/genie/models/oldmodel/ and to train again i am using the following command :
docker run -v /home/ubuntu/genie:/data -v /home/ubuntu/embeddingsseq:/embed checkmount train --load /data/models/oldmodel/best.pth --train_tasks almond --save /data/models/newmodel --cache /data/workdir/cache --data /data/workdir --preserve_case --embeddings /embed --train_iterations 1000 --save_every 500 --log_every 100 --val_every 500 --train_batch_tokens 100 --val_batch_size 128 --model TransformerSeq2Seq --pretrained_model facebook/bart-large --rnn_dimension 768 --rnn_layers 2 --rnn_zero_state average --gradient_accumulation_steps 20 --no_commit

but getting error:

Can't load tokenizer for '/data/models/newmodel'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/data/models/newmodel' is the correct path to a directory containing all relevant tokenizer files.

**Comment by Shisir99** [comment]
@s-jse here are the errors that i am getting
![Screenshot from 2022-03-04 15-31-41](https://user-images.githubuser
![Screenshot from 2022-03-04 15-31-29](https://user-images.githubusercontent.com/43596686/156746265-ca222a6e-99f6-4acd-a6e5-77e60e052214.png)
content.com/43596686/156746255-19964a81-72fb-47ae-8cb7-a6c9a3102322.png)

**Comment by Shisir99** [comment]
![Screenshot from 2022-03-04 17-29-10](https://user-images.githubusercontent.com/43596686/156759685-71912ccc-673f-4e9b-a755-ea16a98709b7.png)
![Screenshot from 2022-03-04 17-29-07](https://user-images.githubusercontent.com/43596686/156759703-ca2946b9-dbca-49cf-b602-f3c512d4fcfc.png)

**Comment by s-jse** [comment]
`best.pth` is not a path, it is the name of the file inside the path specified using `--save`, which should be the same as the old model. See my example train commands above. In your case, you should try running this command:

`docker run -v /home/ubuntu/genie:/data -v /home/ubuntu/embeddingsseq:/embed checkmount train --load best.pth --train_tasks almond --save /home/ubuntu/genie/models/oldmodel/ --cache /data/workdir/cache --data /data/workdir --preserve_case --embeddings /embed --train_iterations 1000 --save_every 500 --log_every 100 --val_every 500 --train_batch_tokens 100 --val_batch_size 128 --model TransformerSeq2Seq --pretrained_model facebook/bart-large --gradient_accumulation_steps 20 --no_commit`

Note that this will overwrite your old model at `/home/ubuntu/genie/models/oldmodel/`, so might want to keep a separate copy of that directory in case you want to use it again.

Also, a few unrelated things I noticed in your command:
- You don't need to specify RNN arguments like `--rnn_dimension 768 --rnn_layers 2 --rnn_zero_state average` since you are using a transformer model (`--model TransformerSeq2Seq`).
- Depending on the device you are training your model on, you might be able to fit larger batches, so try increasing `--train_batch_tokens 100` and `--val_batch_size 128` and see if it fits on your device. Note that these numbers are in **tokens** not number of examples. For example, if each of your training examples has 20 tokens, your train batch size (ignoring `--gradient_accumulation_steps`) is only 5 examples.

**Comment by Shisir99** [comment]
In the command that you shared above(where --save flag is pointed to old model directory) where will the new model be saved? I guess --save flag is for the new location where we want to save the new model.

**Comment by s-jse** [comment]
As I said:
> Note that this will overwrite your old model at /home/ubuntu/genie/models/oldmodel/, so might want to keep a separate copy of that directory in case you want to use it again.

There is not option to save the model in a separate folder, it will overwrite the folder it loads from. If you think another behavior is more reasonable, you can open a separate issue to recommend a change (or a pull request implementing the change!). Though we won't get to it for some time.

**Comment by Shisir99** [comment]
Hello , good morning 
got this new error with the new command you shared :

Traceback (most recent call last):
  File "/usr/bin/genienlp", line 33, in <module>
    sys.exit(load_entry_point('genienlp', 'console_scripts', 'genienlp')())
  File "/opt/genienlp/genienlp/__main__.py", line 108, in main
    subcommands[argv.subcommand][2](argv)
  File "/opt/genienlp/genienlp/train.py", line 671, in main
    model, best_decascore = model_class.load(
  File "/opt/genienlp/genienlp/models/base.py", line 59, in load
    model = cls(args=args, tasks=tasks, vocab_sets=vocab_sets, save_directory=save_directory, *model_args, **kwargs)
  File "/opt/genienlp/genienlp/models/transformer_seq2seq.py", line 73, in __init__
    self.numericalizer = TransformerNumericalizer(
  File "/opt/genienlp/genienlp/data_utils/numericalizer.py", line 130, in __init__
    self._init_tokenizer(save_dir, config, src_lang, tgt_lang)
  File "/opt/genienlp/genienlp/data_utils/numericalizer.py", line 185, in _init_tokenizer
    self._tokenizer = AutoTokenizer.from_pretrained(**tokenizer_args)
  File "/usr/local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 532, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1757, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for '/home/ubuntu/genie/models/oldmodel/'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/home/ubuntu/genie/models/oldmodel/' is the correct path to a directory containing all relevant tokenizer files.

**Comment by s-jse** [comment]
This error message means the directory you are passing to the `--save` argument does not have a tokenizer file in it. This usually happens because the directory you are passing in `--save` is not the correct one, or has some other problem.
Please do the following:

1. Make sure you are running **two** training commands. The first one is the normal training command that you had before, which did NOT have `--load best.pth`. This creates a model directory. The second training command takes the same model directory in `--save`, and has an additional `--load best.pth`.

1. The command I posted above might have had the wrong model directory in `--save`: `--save /home/ubuntu/genie/models/oldmodel/`. Make sure you are passing the actual directory that contains your model, which seems to be  `--save /data/models/oldmodel`.

1. So that I can double check, please paste the full training commands you are running here, both the initial train command, and the new one which has `--load best.pth`.

**Comment by Shisir99** [comment]
I have model stored in oldmodel , attaching the ss for your reference.
for the second time i am using following command :
docker run -v /home/ubuntu/genie:/data -v /home/ubuntu/embeddingsseq:/embed checkmount train --load best.pth --train_tasks almond --save /home/ubuntu/genie/models/oldmodel --cache /data/workdir/cache --data /data/workdir --preserve_case --embeddings /embed --train_iterations 1000 --save_every 500 --log_every 100 --val_every 500 --train_batch_tokens 100 --val_batch_size 128 --model TransformerSeq2Seq --pretrained_model facebook/bart-large --gradient_accumulation_ste
![Screenshot from 2022-03-07 10-21-17](https://user-images.githubusercontent.com/43596686/156970080-b4d84677-9f4d-4827-9e07-db11beb50c82.png)
ps 20 --no_commit

**Comment by Mehrad0711** [comment]
Hi @Shisir99,

The problem might be that you have used a different version of genienlp or transformers library for training the first model. Thus the model name can not be resolved by huggingface properly when loading it with a newer version.
Unfortunately, I can not reproduce the error you've posted with the latest version of genienlp.

Can you please share with us the commands you're using for (1) training the model, and (2) fine-tuning it, along with the genienlp version/ commit hash you're using.

**Comment by Shisir99** [comment]
Hello, i used the following command for training the first model:

docker run -v /home/ubuntu/genie:/data -v /home/ubuntu/embeddingsseq:/embed checkmount train --train_tasks almond --save /home/ubuntu/genie/models/oldmodel/ --cache /data/workdir/cache --data /data/workdir --preserve_case --embeddings /embed --train_iterations 1000 --save_every 500 --log_every 100 --val_every 500 --train_batch_tokens 100 --val_batch_size 128 --model TransformerSeq2Seq --pretrained_model facebook/bart-large --gradient_accumulation_steps 20 --no_commit

and for the second time i used(at this time i have a model stored in oldmodel directory):

docker run -v /home/ubuntu/genie:/data -v /home/ubuntu/embeddingsseq:/embed checkmount train --load best.pth --train_tasks almond --save /home/ubuntu/genie/models/oldmodel/ --cache /data/workdir/cache --data /data/workdir --preserve_case --embeddings /embed --train_iterations 1000 --save_every 500 --log_every 100 --val_every 500 --train_batch_tokens 100 --val_batch_size 128 --model TransformerSeq2Seq --pretrained_model facebook/bart-large --gradient_accumulation_steps 20 --no_commit

**Comment by Shisir99** [comment]
this is the dockerfile used to generate the genienlp image:

FROM stanfordoval/genienlp:latest

WORKDIR /gennlp

USER root

RUN mkdir -p models

**Comment by Mehrad0711** [comment]
Since you're pulling `genienlp:latest`, depending on when you've built your docker, you may have a different version of genienlp than the current master. The latest docker is pushed every time we merge a new PR into the master branch.

I ran your commands on master branch (commit hash: `0176a87fcdd354552ce62fa37fb096685a691029`), and it's running fine without errors.

I suggest the following steps to make sure you get a clean run:
- Rebuilding your docker image (which will use the current master)
- Deleting all cached embedding files. I see you're mounting volumes hosting those embeddings. Make sure those are updated when you rerun the genienlp commands using the new image. Specifically, you need to use transformers==4.17.0.

If the problem still persists, try running same commands outside of docker.

**Comment by Shisir99** [comment]
tried this outside the docker.
first image attached is the training for first model and the second image attached is for training again(transfer learning).
![Screenshot from 2022-03-16 13-37-28](https://user-images.githubusercontent.com/43596686/158544898-c6ece4e7-a64a-4334-a721-d833e336f4b4.png)
![Screenshot from 2022-03-16 13-37-32](https://user-images.githubusercontent.com/43596686/158544924-214395fc-2572-48a7-b80c-ea0e94361cf4.png)

**Comment by Mehrad0711** [comment]
@Shisir99 you're still running with an old version of genienlp! We have removed the `--cache` argument in the latest version.
As I mentioned, please use the current master branch.

**Comment by Mehrad0711** [comment]
Also, the error here is because the code is trying to recreate a directory that already exists. Please pass `--exist_ok` to your second command to avoid this.

**Comment by Shisir99** [comment]
It's okay, we need to pass an extra argument --exist_ok for transfer learning.
Thanks for your help, closing this issue.

**Comment by Shisir99** [comment]
Thanks, it's working now.

**Comment by Shisir99** [comment]
At first i had a model trained on demo.tea skill and on the top of that i trained a model on order.pizza skill but as you can see in the screenshot the model is only replying with the latter one i.e. order.pizza as the output no matter which question i ask.


![Screenshot from 2022-03-25 16-17-40](https://user-images.githubusercontent.com/43596686/160106934-38bcb72f-fccd-49b9-a5bc-31d58a32e316.png)

**Comment by s-jse** [comment]
What you are seeing is a case of [catastrophic forgetting](https://en.wikipedia.org/wiki/Catastrophic_interference), meaning that the neural network forgets almost all of what it learned during the first training, and only remembers the most recent training examples from the second training. This happens all the time to varying degrees, especially with larger models and larger training sets that are commonplace these days.

In general, if your goal is to have a model that can understand both tea and pizza domains, the best thing to do is to simply mix their training and validation sets (i.e. concatenate the two `train.tsv`s and the two `eval.tsv`s) and train the model on this combination at once.

What you have done (two-step training or transfer learning) would be more useful if your goal was to have a model that performs well in the second domain (pizza), and you wanted to improve the accuracy in that domain by first training on tea so that the model learns some potentially transferable things like the syntax of the output.
